"""Authorized Metadata catalog feature."""

from gds_workbench_api.features.metadata.contracts import (
    FOUNDATIONAL_DATASETS,
    MAX_METADATA_EXPORT_ROWS,
    MAX_METADATA_EXPORT_ROWS_PER_SHEET,
    METADATA_DATASETS,
    OPERATIONAL_DATASETS,
    REFERENCE_DATASETS,
    MetadataDatabase,
    MetadataDataset,
    MetadataDatasetDescription,
    MetadataDatasetDetail,
    MetadataDatasetRegistry,
    MetadataFilter,
    MetadataObjectNotFoundError,
    MetadataRepository,
    MetadataRowPage,
    MetadataService,
    MetadataWorkbookDownload,
    ObjectAttribute,
    ObjectCatalogDetail,
    ObjectCatalogFilters,
    ObjectCatalogPage,
    ObjectCatalogSummary,
    OperationalDataset,
)
from gds_workbench_api.features.metadata.repository import PostgresMetadataRepository
from gds_workbench_api.features.metadata.router import create_metadata_router
from gds_workbench_api.features.metadata.service import (
    DatabaseMetadataService,
    metadata_dataset_detail,
    metadata_dataset_registry,
)

__all__ = [
    "DatabaseMetadataService",
    "FOUNDATIONAL_DATASETS",
    "MAX_METADATA_EXPORT_ROWS",
    "MAX_METADATA_EXPORT_ROWS_PER_SHEET",
    "METADATA_DATASETS",
    "OPERATIONAL_DATASETS",
    "ObjectAttribute",
    "ObjectCatalogDetail",
    "ObjectCatalogFilters",
    "ObjectCatalogPage",
    "ObjectCatalogSummary",
    "OperationalDataset",
    "PostgresMetadataRepository",
    "REFERENCE_DATASETS",
    "MetadataDatabase",
    "MetadataDataset",
    "MetadataDatasetDescription",
    "MetadataDatasetDetail",
    "MetadataDatasetRegistry",
    "MetadataFilter",
    "MetadataObjectNotFoundError",
    "MetadataRepository",
    "MetadataRowPage",
    "MetadataService",
    "MetadataWorkbookDownload",
    "create_metadata_router",
    "metadata_dataset_detail",
    "metadata_dataset_registry",
]
